#!/bin/bash

for t in bin/*; do 
	shasum=$(md5sum $t)
	util/update-modules $t; 
	updated_shasum=$(md5sum $t)
	if [ "$shasum" != "$updated_shasum" ]; then
		echo "$t had unsynced changes from lib, md5sum before and after running './util/update-modules $t' is different"
		exit 1
	fi
done
